name: imagebuilder
home: https://github.com/drycc/imagebuilder
apiVersion: v2
appVersion: 1.0.0
version: v1.0.0
description: Imagebuilder application builder for Drycc Workflow.
maintainers:
  - name: Drycc Team
    email: engineering@drycc.com
