#!/usr/bin/env bash
set -eo pipefail

CADDY_DOWNLOAD_URL="https://github.com/caddyserver/caddy/releases/download/v2.4.3/caddy_2.4.3_linux_$(dpkg --print-architecture).tar.gz"
(curl -sSL "${CADDY_DOWNLOAD_URL}" | tar -C /usr/local/bin/ --no-same-owner -xzv caddy)

apt-get autoremove -y --purge
apt-get clean all
rm -rf /root/*
rm -rf /tmp/*
rm -rf /var/cache/apt/archives/*.deb
rm -rf /var/lib/apt/lists/*
