apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: drycc-imagebuilder
spec:
  podSelector:
    matchLabels:
      app: drycc-imagebuilder
  policyTypes:
  - Egress
  egress:
  - to:
    ports:
    - protocol: UDP
      port: 53
  - to:
    - ipBlock:
        cidr: ::/0
        except:
        - fc00::/7
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Name }}
    - podSelector:
        matchLabels:
          app: drycc-registry
    ports:
    - protocol: TCP
      port: 5000
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Name }}
    - podSelector:
        matchLabels:
          app: drycc-storage
    ports:
    - protocol: TCP
      port: 9000
