apiVersion: v1
kind: ConfigMap
metadata:
  name: imagebuilder-config
  labels:
    heritage: drycc
data:
  buildpacks: "{{.Values.imageRegistry}}/{{.Values.imageOrg}}/buildpacks:bullseye"
  images.json: |
    [
        {
            "name": "container",
            "image": "{{.Values.imageRegistry}}/{{.Values.imageOrg}}/imagebuilder:{{.Values.imageTag}}"
        },
        {
            "name": "buildpack",
            "image": "{{.Values.imageRegistry}}/{{.Values.imageOrg}}/imagebuilder:{{.Values.imageTag}}"
        }
    ]
  registries.conf: |
    {{- .Values.containerRegistries | nindent 4 }}
  imagePullPolicy: {{ .Values.imagePullPolicy }}
