apiVersion: v1
kind: ConfigMap
metadata:
  name: imagebuilder-config
  labels:
    heritage: drycc
data:
  images.json: |
    [
        {
            "name": "container",
            "image": "{{.Values.image_registry}}/{{.Values.image_org}}/imagebuilder:{{.Values.image_tag}}"
        },
        {
            "name": "buildpack",
            "image": "{{.Values.image_registry}}/{{.Values.image_org}}/imagebuilder:{{.Values.image_tag}}"
        }
    ]
  registries.conf: |
    {{- .Values.container_registries | nindent 4 }}
  image_pull_policy: {{ .Values.image_pull_policy }}
